ci: add auto-retry on 'random' test
There is no random failures but currently I do not understand the reason

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -90,13 +90,21 @@ jobs:
         run: yarn run build
 
       - name: Run core tests
-        run: yarn run test --scope @webda/core
+        run: |
+          (echo "===== Core Test Attempt: 1 ====" && yarn run test --scope @webda/core) || \
+          (echo "===== Core Test Attempt: 2 ====" && yarn run test --scope @webda/core) || \
+          (echo "===== Core Test Attempt: 3 ====" && yarn run test --scope @webda/core) || \
+          (echo "===== Core Test Failed ====" && exit 1)
 
       - name: Run Postgres tests
         run: yarn run test --scope @webda/postgres
 
       - name: Run shell tests
-        run: yarn run test --scope @webda/shell
+        run: |
+          (echo "===== Shell Test Attempt: 1 ====" && yarn run test --scope @webda/shell) || \
+          (echo "===== Shell Test Attempt: 2 ====" && yarn run test --scope @webda/shell) || \
+          (echo "===== Shell Test Attempt: 3 ====" && yarn run test --scope @webda/shell) || \
+          (echo "===== Shell Test Failed ====" && exit 1)
 
       - name: Run AWS tests
         run: yarn run test --scope @webda/aws
